server:
  port: 5000
  
  
spring:
  data:
    mongodb:
      host: ${MONGO_URI}
      port: ${MONGO_PORT}
      database: bankingAccount
      username: ${MONGO_USER}
      password: ${MONGO_PASS}
      authentication-database: admin
      
      
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_URL}:${KAFKA_PORT}
      key-serializer: org.apace.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        