server:
  port: 5001
  
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:${POSTGRES_PORT}/bankingAccount
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: ${KAFKA_URL}:${KAFKA_PORT}
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apace.kafka.common.serialization.StringDeSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeSerializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
